apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "name" is the name of the ClusterRole
  name: pod-node-reader
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Pod
  # is "pods" and the name of the resource for accessing Node
  # is "nodes"
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
