apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-nodes
subjects:
- kind: User
  # Name is case sensitive
  name: "arn:aws:iam::129592407301:role/eks-fargate-pod-execution-role"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-node-reader
  apiGroup: rbac.authorization.k8s.io
